TYPE=VIEW
query=select `projekt`.`gatunek`.`IDGatunku` AS `IDGatunku`,`projekt`.`gatunek`.`Gatunek` AS `Gatunek` from `projekt`.`gatunek`
md5=96be3773bdef9d7bd93db5aff798a1f4
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2022-06-06 11:13:50
create-version=2
source=select `gatunek`.`IDGatunku` AS `IDGatunku`,`gatunek`.`Gatunek` AS `Gatunek` from `gatunek`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `projekt`.`gatunek`.`IDGatunku` AS `IDGatunku`,`projekt`.`gatunek`.`Gatunek` AS `Gatunek` from `projekt`.`gatunek`
mariadb-version=100424
