TYPE=VIEW
query=select `projekt`.`pegi`.`IDPEGI` AS `IDPEGI`,`projekt`.`pegi`.`PEGI` AS `PEGI` from `projekt`.`pegi`
md5=85a79df754f3a756b637506cb7e84427
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2022-06-06 11:13:50
create-version=2
source=select `pegi`.`IDPEGI` AS `IDPEGI`,`pegi`.`PEGI` AS `PEGI` from `pegi`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `projekt`.`pegi`.`IDPEGI` AS `IDPEGI`,`projekt`.`pegi`.`PEGI` AS `PEGI` from `projekt`.`pegi`
mariadb-version=100424
